name: Pytest Automation with Allure and HTML Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    env:
      PYTHON_VERSION: '3.12.4'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create Virtual Environment
        run: |
          python -m venv venv

      - name: Activate Virtual Env and Install Dependencies
        run: |
          .\venv\Scripts\activate
          pip install -r requirements.txt
        shell: pwsh

      - name: Prepare Directories
        run: |
          mkdir reports
          mkdir logs
          mkdir pytest-html
        shell: pwsh

      - name: Run Tests with Allure, HTML Report, and Logs
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
          $htmlReport = "pytest-html/report_$timestamp.html"
          $logFile = "logs/test_log_$timestamp.log"
          .\venv\Scripts\activate
          echo "import logging; logging.basicConfig(filename='$logFile', level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')" > log_config.py
          pytest -v -s ./tests/test_parabank.py --alluredir=reports/allure-result --html="$htmlReport" --self-contained-html
        shell: pwsh

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: reports/allure-result

      - name: Upload pytest-html Report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-html-report
          path: pytest-html/*.html

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: logs/*.log

      - name: Generate and Publish Allure Report (GitHub Pages)
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: reports/allure-result
          allure_report: reports/allure-report
          gh_pages: gh-pages
