name: ParaBank Test Automation

on:
  push:
    branches: [ bredlin ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest pytest-html faker

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
        sudo tar -zxvf allure-2.24.0.tgz -C /opt/
        sudo ln -s /opt/allure-2.24.0/bin/allure /usr/bin/allure

    - name: Run tests
      id: pytest
      continue-on-error: true
      run: |
        mkdir -p test-results/allure-results
        mkdir -p test-results/html-reports
        mkdir -p test-results/logs
        pytest --headless -v --alluredir=./test-results/allure-results --clean-alluredir

    - name: Generate Allure report
      if: always()
      run: |
        allure generate "./test-results/allure-results" -o "./test-results/allure-report" --clean

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/

    - name: Deploy reports to gh-pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-results
        publish_branch: gh-pages
        destination_dir: test-results
